### ISSUE TITLE
"Towards Automatic Concept-based Explanations"?

### ISSUE THREAD

**Issue by kennysong** [dmitrykazhdan/concept-based-xai#2]
Hi, nice paper! I'm curious why "Towards Automatic Concept-based Explanations" wasn't mentioned in the paper and repo. As far as I know, it's the only unsupervised concept-based technique.

(Not an expert.)

**Comment by dmitrykazhdan** [comment]
Hi Kenny,
Thank you for your inquiry. 
We have included the "On Completeness Aware Concept-based Explanations" (OCACE) method in this repo. OCACE is a more recent approach to unsupervised concept extraction, which improves on ACE (see paper here: https://arxiv.org/abs/1910.07969).
We are considering adding ACE as well in the future for completeness/reference.
